### PR TITLE
Extend subscription filter capabilities

### LINKED ISSUE #1533: [CON-50] Support JSON Payload with an array at the root.
Currently, if your JSON Payload has an array at the root, the subscriptions filtering system fails to match it. The logs show the following:
```bash
Failed to match subscription filter json: cannot unmarshal array into Go value of type map[string]interface {}","time":"2023-04-08 01:23:25"}
```

**Sample Payload**
```json[sample payload]
{
  "data": [
    {
        "event" : "test.message"
    }
  ],
  "endpoint_id": "01GXCAZTT15B734KVDPKMY8VTM",
  "event_type": "test.message"
}
```

<sub>[CON-50](https://linear.app/convoy-engineering/issue/CON-50/support-json-payload-with-an-array-at-the-root)</sub>

### LINKED ISSUE #1534: Subscription filter issues in the latest release
Latest version (0.9.1) ignore subscription filter to discard or to route messages.

### PR DESCRIPTION
**Pull request by jirevwe**
Resolves #1533
Fixes #1534
Adds support for event payloads with array at the JSON root and nested JSON objects up to 3 levels

### CODE REVIEW

File: pkg/compare/compare.go [hunk 1]
```diff
@@ -171,6 +189,8 @@ func eq(x, y interface{}) bool {
 		y = fy
 	}
 
+	fmt.Printf("x: %v y: %v\n", x, y)
```
Comment (Subomi) [inline pkg/compare/compare.go:192]: @jirevwe, I think you forgot to remove this.

**Review by Dotunj — APPROVED** [review]

**Review by Subomi — APPROVED** [review]

**Review by danvixent — APPROVED** [review]
